.TH SSI 1 "Sep 2022" "ssi"
.SH NAME
ssi
\- some system information
.SH SYNOPSIS
.B ssi
[\fIoptions\fP]
.SH DESCRIPTION
Prints total number of threads on the machine and date/time in the local
timezone to the standard output.
.SH OPTIONS
.TP
\fB\-v\fR
print version
.TP
\fB\-h\fR
show help message
.SH AUTHORS
Konstantin Trushin <konstantin.trushin@gmail.com>
.PP
This manual page was written by Konstantin Trushin
<konstantin.trushin@gmail.com>.
Permission is granted to redistribute, use, and/or modify this document under
the same terms as ssi itself.
