FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM linux

ARG username
ARG uid
ARG gid
ARG locale=en_US.UTF-8


# Add PPA with meson 0.52.0
# plese see https://launchpad.net/~jonathonf/+archive/ubuntu/meson
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        software-properties-common && \
    add-apt-repository ppa:jonathonf/meson && \
    apt-get update

# Don't drop man pages and other files from the packages being installed
RUN mv /etc/dpkg/dpkg.cfg.d/excludes /tmp/dpkg_excludes.bk
# Reinstall all already installed packages in order to get the man pages back
RUN dpkg -l | grep ^ii | cut -d' ' -f3 | \
        xargs apt-get install --yes --no-install-recommends --reinstall

# Create the user
RUN addgroup --gid $gid $username && \
    adduser --uid $uid --gid $gid --home /home/$username \
        --disabled-password --gecos '' $username && \
    adduser $username sudo && \
    mkdir -p /etc/sudoers.d/ && \
    echo "$username ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$username
ENV LOGNAME=$username \
    USER=$username

# Set the locale
RUN apt-get install --yes --no-install-recommends locales
RUN locale-gen $locale && update-locale LANG=$locale LC_CTYPE=$locale
ENV LANG=$locale \
    LC_ALL=$locale

# Install the packages for C++ development and convenient command line usage
RUN apt-get install --yes --no-install-recommends \
        sudo apt-utils lsb-release software-properties-common tzdata \
        bash-completion coreutils less tree tmux vim gnupg2 ca-certificates \
        man-db manpages manpages-dev \
        git-core \
        gcc-8 g++-8 \
        clang-8 clang-format-8 clang-tidy-8 \
        ccache \
        autoconf automake m4 autotools-dev libtool \
        make ninja-build \
        cmake cmake-data\
        gdb lldb-8 \
        build-essential debhelper devscripts fakeroot dput \
        libboost1.65-all-dev libjemalloc-dev \
        python3 python3-dev python3-setuptools python3-pip python3-wheel \
        # The following package is from the PPA
        meson=0.52.0-2~18.04.york0

ENV CCACHE_DIR=/var/c_cache \
    PYTHONDONTWRITEBYTECODE=1
RUN mkdir -p $CCACHE_DIR && \
    chown $username:$username $CCACHE_DIR
